### ISSUE TITLE
Default server - specify port?

### ISSUE THREAD

**Issue by cscd98** [pgassmann/puppet-letsencrypt_nginx#15]
I already have Varnish on port 80, with nginx on port 8080.

Is there any way to specify a port?

**Comment by pgassmann** [comment]
It does not make sense to use a different port. letsencrypt needs port 80, plain http. if nginx is already running, you just have to add the location first.

**Comment by cscd98** [comment]
@pgassmann with regards to default_server_name variable, can you check if it is false or undef here before using it:

```
ensure_resource('letsencrypt_nginx::location', $default_server_name )
```

That way, I can pass default_server_name to false or undef from my node, thereby bypassing create the default location in default server.

**Comment by pgassmann** [comment]
You can create a merge request, then I can merge it.
Can you create an example.pp where you show how you use this?

**Comment by cscd98** [comment]
Example usage:

```
class { 'letsencrypt_nginx':
      firstrun_webroot => '/usr/share/nginx/html',
      servers           => {
        'www.xx.com' => {},
      },
      default_server_name => false
    }
```

https://github.com/pgassmann/puppet-letsencrypt_nginx/pull/16

**Comment by cscd98** [comment]
PS the plugin is correctly now adding:

```
location /.well-known/acme-challenge {
    auth_basic           "off";
    root      /var/lib/letsencrypt/webroot;
    index     index.html index.htm index.php;
  }
```

to my vhost config at the bottom.

But, when I run puppet I get:
```
http://www.xx.com/.well-known/acme-challenge/some-rand-var
```

404.

Is there supposed to be a file located in /usr/share/nginx/html or /var/lib/letsencrypt/webroot as the folder is empty?

**Comment by pgassmann** [comment]
what is your `nginx::server` resource? is your nginx server already running and available through http://www.xx.com/ ?
The default_server is the server configuration that will respond to any domain requested on that machine that is not explicitly configured.
If you use just one domain on that machine, you can specify the name of your nginx::server 'www.xx.com' as `$default_server_name` instead of setting it to `false`

this module will call `letsencrypt::certonly` which will write the challenge response into the separate webroot to get the certificate
https://github.com/pgassmann/puppet-letsencrypt_nginx/blob/master/manifests/server.pp#L96

The module is designed so that it can configure the ssl certificate in one run on a freshly installed server. On ubuntu, nginx is started directly when the package is installed. For this case the firstrun_webroot option is designed, so that the letsencrypt challenge is successful by writing the answer in the webroot that is active directly after installing nginx. If you already have a running nginx server config, all requests will be served by this server, so you need to first configure the `letsencrypt::nginx::location` in one run, so that the new configuration is loaded by nginx. From then on, the challenge responses are served from `/var/lib/letsencrypt/webroot`
